config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.root :controller => "channels"
  
  # Naming the Admin Routes
  map.admins          "admins",               :controller => "admins"
  map.signup          "signup",               :controller => "admins",   :action => "new"
  map.edit_admin      "admins/edit/:id",      :controller => "admins",   :action => "edit"
  map.admin           "admins/show/:id",      :controller => "admins",   :action => "show"
  map.destroy_admin   "admins/destroy/:id",   :controller => "admins",   :action => "destroy"
  
  # Naming the Channel Routes
  map.channels        "channels",             :controller => "channels"
  map.new_channel     "channels/new",         :controller => "channels", :action => "new"
  map.edit_channel    "channels/edit/:id",    :controller => "channels", :action => "edit"
  map.channel         "channels/show/:id",    :controller => "channels", :action => "show"
  map.destroy_channel "channels/destroy/:id", :controller => "channels", :action => "destroy"
  
  # Naming the Session Routes
  map.login           "login",                :controller => "sessions", :action => "new"
  
  # Naming the Triggers Routes
  map.edit_trigger    "triggers/edit/:id",    :controller => "triggers", :action => "edit"
  map.trigger         "triggers/show/:id",    :controller => "triggers", :action => "show"
  map.destroy_trigger "triggers/destroy/:id", :controller => "triggers", :action => "destroy"
  
  # Default Routes
  map.connect         ':controller/:action/:id'
  map.connect         ':controller/:action/:id.:format'
end

app/models/admin.rb
require "digest/md5"

class Admin < ActiveRecord::Base
  attr_accessor :password
  has_many :triggers
  has_and_belongs_to_many :channels
  
  # validation 
  validates_length_of	  	:email,     :within => 3..100 
  validates_uniqueness_of	:email,	  	:case_sensitive => false 
  validates_uniqueness_of	:login,     :case_sensitive => false
  validates_presence_of   :login, :email
  validates_length_of	  	:password,	:within => 4..40, 
										      :if =>      :password_required? 
  validates_confirmation_of :password,	:if => :password_required? 
  
  # callbacks
  before_save :encrypt_password
  
  # authenticate by email/password 
  def self.authenticate(login, pass) 
    admin = find_by_login(login) 
    admin && admin.authenticated?(pass) ? admin : nil 
  end
  
  # does the given password match the stored encrypted password 
  def authenticated?(pass) 
    hashed_password == Admin.encrypt(pass) 
  end

  # sha1 a password
  def self.encrypt(pass)
    Digest::MD5.hexdigest(pass)
  end
  
  # returns longest name possible
  def longest_name
    self.name == "" ? self.login.humanize : self.name
  end
  
  protected
    # encrypt a users password
    def encrypt_password
      return if password.blank?
      self.hashed_password = Admin.encrypt(password)
    end
  
    # no encrypted password yet OR password attribute is set 
    def password_required? 
      hashed_password.blank? || !password.blank?
    end
end

app/views/admins/_admin.haml
.item.admin
  %h4= link_to h(admin.longest_name), admin
  
  - if logged_in? and (is_global? or admin.id == @current_admin.id)
    %p.edit
      = link_to "Edit", edit_admin_path(admin)
      %span /
      = link_to "Delete", destroy_admin_path(admin), :confirm => "Are you sure you want to delete " + admin.longest_name + "?"
  
  %ul
    - if admin.global
      %li= admin.longest_name + " is a <strong>global admin</strong>, and has control over everything. Muahaha..."
    - else
      %li= admin.longest_name + " is a <strong>local admin</strong>, and is constantly overrided by global admins. :("

app/views/admins/_form.haml
= error_messages_for :admin

%p
  %label Login:<br />
  = text_field :admin, :login

%p
  %label Real Name:<br />
  = text_field :admin, :name
  %span.optional (Optional)

%p
  %label Email:<br />
  = text_field :admin, :email

%p
  %label Password:<br />
  = password_field :admin, :password

%p
  %label Confirm Password:<br />
  = password_field :admin, :password_confirmation

- unless params[:action] == "new"
  %p
    %label Global Admin?
    - if logged_in? and @current_admin.global
      = check_box :admin, :global
    - else
      = h @admin.global

  - if is_global? # Make sure the admin doing this is global
    - unless @admin.global # Don't show this if editing a global admin; their access to everything is implied
      %p
        %label Channels<br />
        = select_tag("channels[]", options_for_select(Channel.find(:all).collect {|c| [c.name, c.id] }, @admin.channel_ids), :multiple => true)

app/views/admins/edit.haml
%h2 Editing Admin

- form_tag :action => "update", :id => @admin.id do
  = render :partial => "form", :locals => {:admin => @admin}
  %p= submit_tag_or_cancel "Update"

app/views/admins/index.haml
%h2 All Help Bot Admins

= link_to_new "Admin", signup_path

= render :partial => "admin", :collection => @admins

app/views/admins/new.haml
- if logged_in?
  %h2 New Admin
  %p.notice.caution After submitting this form, you will be logged out and then logged in as the new admin.
- else
  %h2 Sign Up

- form_tag :action => "create" do
  = render :partial => "form"
  %p= submit_tag "Sign Up"

app/views/admins/show.haml
%h2 Admin

= link_to_new "Admin", signup_path

= render :partial => "admin", :object => @admin

%h3= @admin.longest_name + "&#8217;s Channels"

- if @admin.global
  .dim= render :partial => "channels/channel", :collection => Channel.find(:all)
- else
  - if @admin.channels == []
    %p.notice.error= "None. " + @admin.longest_name + " does not have power over any channels. :("
  - else
    .dim= render :partial => "channels/channel", :collection => @admin.channels